### ISSUE TITLE
epic: create, complete, and remove item

### ISSUE THREAD

**Issue by jbradenbrown** [Vhynn/ToDoApp#5]
## Overview
Items can be added to each list, and items can be clicked to mark them as completed. Completed items can also be cleared to clean up the space.

## Spikes
- [x] Basic Javascript Familiarity
- [x] Browser Dev Tools
- [x] How to connect a JS function to a browser event
- [x] How to manipulate a webpage from JS

## Features
- [x] #6
- [x] #8
- [x] Clicking on the button to clean the lists will remove all completed items

## References
[The DOM](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Manipulating_documents)
[JS Basics](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps)
[Browser Events (video)](https://www.youtube.com/watch?v=LeKKU3a4AQo)
[Event Listeners (more advanced video)](https://www.youtube.com/watch?v=XF1_MlZ5l6M)
[Functional Programming in JS (video)](https://www.youtube.com/watch?v=BMUiFMZr7vk) I really like this channel

**Comment by Vhynn** [comment]
All features are working now.
